---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-system
  labels:
    app: traefik
spec:
  type: NodePort
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: websecure
      port: 443
      targetPort: 443
      nodePort: 30443
    - name: dashboard
      port: 8080
      targetPort: 8080
      nodePort: 30808
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: traefik-system
  labels:
    app: traefik
spec:
  selector:
    app: traefik
  ports:
    - name: dashboard
      port: 8080
      targetPort: 8080
