apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: service-a-ingress
  namespace: microservices
  labels:
    app: service-a
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`service-a.test`)
      kind: Rule
      services:
        - name: service-a
          port: 80
