apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - grafana-ingressroute.yaml

patches:
  - path: grafana-service-patch.yaml
  - path: loki-storage-patch.yaml
