apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Smaller for local
  storageClassName: standard
