apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: service-b-ingress
  namespace: microservices
  labels:
    app: service-b
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`service-b.test`)
      kind: Rule
      services:
        - name: service-b
          port: 80
