apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - persistentvolumeclaim.yaml
  - secret.yaml

labels:
  - includeSelectors: true
    pairs:
      app: grafana
      component: observability
