apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: logging
  labels:
    app: grafana
    component: observability
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: grafana
