apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - persistentvolumeclaim.yaml

labels:
  - includeSelectors: true
    pairs:
      app: loki
      component: logging
