apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: service-b
spec:
  selector:
    app: service-b
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
